MONTADOR_SRC = montador.cpp
MONTADOR_OUT = montador

LIGADOR_SRC = ligador.cpp
LIGADOR_OUT = ligador

all:
	g++ -Wall $(MONTADOR_SRC) -o $(MONTADOR_OUT)
	g++ -Wall $(LIGADOR_SRC) -o $(LIGADOR_OUT)

clean:
	rm $(MONTADOR_OUT)
	rm $(LIGADOR_OUT)
